# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    com.docker.official-images.bashbrew.arch/configurator-db: amd64
    io.kubernetes.cri-o.ContainerType/configurator-db: container
    io.kubernetes.cri-o.SandboxID/configurator-db: c35138e9dde790d3ce269bc1b061efc34ae634948c0b2a21ca70612a0b59f47
    io.kubernetes.cri-o.TTY/configurator-db: "false"
    io.podman.annotations.autoremove/configurator-db: "FALSE"
    io.podman.annotations.init/configurator-db: "FALSE"
    io.podman.annotations.privileged/configurator-db: "FALSE"
    io.podman.annotations.publish-all/configurator-db: "FALSE"
    org.opencontainers.image.base.digest/configurator-db: sha256:44bccdd61bf09a081b1db8c61cf49bfabf30ac7afcc970010137c0ab
    org.opencontainers.image.base.name/configurator-db: debian:bookworm-slim
    org.opencontainers.image.created/configurator-db: "2025-02-04T00:55:44Z"
    org.opencontainers.image.revision/configurator-db: 042d8d043fed77e0e09b6fcda0991bca9e8664e3
    org.opencontainers.image.source/configurator-db: https://github.com/docker-library/postgres.git#042d8d043fed77e0
    org.opencontainers.image.url/configurator-db: https://hub.docker.com/_/postgres
    org.opencontainers.image.version/configurator-db: "17.2"
  creationTimestamp: "2025-02-06T22:19:25Z"
  labels:
    app: anovel-kit-configurator-test
  name: anovel-kit-configurator-test
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_DB
      value: test
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    - name: POSTGRES_PASSWORD
      value: test
    - name: POSTGRES_USER
      value: test
    image: docker.io/library/postgres:17
    name: configurator-db
    ports:
    - containerPort: 5432
      hostPort: 5432
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: 47870c341f31b19c21f15098c0c9e2fd67fb67602ce5ae04cc4f867ac6a5b7c8-pvc
  enableServiceLinks: false
  hostname: anovel-kit-configurator-test
  restartPolicy: Always
  volumes:
  - name: 47870c341f31b19c21f15098c0c9e2fd67fb67602ce5ae04cc4f867ac6a5b7c8-pvc
    persistentVolumeClaim:
      claimName: 47870c341f31b19c21f15098c0c9e2fd67fb67602ce5ae04cc4f867ac6a5b7c8
status: {}

